create database student 
go
use student 
go
create table students(
    ID varchar(10),
	NAME VARCHAR(50),
	ADDRESS VARCHAR(20),
	GPA FLOAT,
	BIRTH DATE
)
INSERT INTO STUDENTS VALUES
('SV001','NGUYEN VAN NAM','HAI DUONG',3.2,'2002-02-10')
INSERT INTO STUDENTS VALUES
('SV002', 'Hoang Dinh Nam', 'Ha Noi' ,2.8,'1999-08-08')
INSERT INTO STUDENTS VALUES
('SV003','Pham Ngoc Thuan','Nam Dinh',2.2,'1999-12-20')
INSERT INTO STUDENTS VALUES
('SV004','Nguyen Duc Xuan','Thai Binh',2.1,'1999-07-18')
INSERT INTO STUDENTS VALUES
('SV005','Hoang Van Long','Ha Noi',3.4,'2001-10-10')
INSERT INTO STUDENTS VALUES
('SV006','Nguyen Ngoc Long','Nam Dinh',3.1,'2001-12-19')
INSERT INTO STUDENTS VALUES
('SV007','Nguyen Thuy Linh','Hai Duong',3.7,'2001-03-03')
INSERT INTO STUDENTS VALUES
('SV008','Nguyen Thuy Huong','Nghe An',2.8,'1999-04-20')
SELECT * FROM STUDENTS
SELECT ID,NAME,GPA FROM STUDENTS
WHERE GPA>3.2
SELECT * FROM STUDENTS WHERE ADDRESS ='HAI DUONG'
SELECT * FROM STUDENTS WHERE ADDRESS='NAM DINH' AND GPA>3.2
SELECT * FROM STUDENTS WHERE GPA>2.5 AND GPA<3.2
SELECT * From STUDENTS WHERE NAME LIKE 'h%' or name like 'p%'
select * from students where ((name like '%g' or name like '%m') and len(name)>5)
SELECT * FROM STUDENTS WHERE ((ADDRESS ='NAM DINH' OR ADDRESS ='HAI DUONG') AND YEAR(BIRTH)>2000)
SELECT *
FROM STUDENTS
WHERE NAME LIKE '%[a-h]%';
update students
set GPA=3.9
where ID ='SV001' 
select TOP 4* FROM STUDENTS
--HAM SQL MIN  VA MAX
SELECT MIN(NAME) FROM STUDENTS
--HAM SQL COUNT : TRA VE SO LUONG 
SELECT COUNT(*) FROM STUDENTS
SELECT COUNT(GPA) FROM STUDENTS WHERE GPA>2.2
--HAM SQL SUM()
SELECT SUM(GPA) FROM STUDENTS WHERE GPA>2.2
--HAM SQL TINH GIA TRI TRUNG BING
SELECT AVG(GPA) AS 'GIA TRI TRUNG BINH LA' FROM STUDENTS
SELECT * FROM STUDENTS WHERE GPA> (SELECT AVG(GPA) FROM STUDENTS)
--TOAN TU SQL IN (LA GOP CUA TOAN TU ORR)
SELECT * FROM STUDENTS WHERE ADDRESS IN('HAI DUONG','NAM DINH') 
-- TOAN TU SQL BETWEEN
SELECT * FROM STUDENTS WHERE GPA BETWEEN 2.2 AND 3.6
--SQL ALIASES
SELECT ID AS 'MA SINH VIEN' FROM STUDENTS
/*
--SQL JOINS
-- JOIN CHIA RA LAM 4 LOAI CHINH DO LA INNER JOINS ,LEFT JOINS,RIGHT JOINS VA FULL OUTER JOINS
-- INNER JOIN
SELECT ProductID, ProductName, CategoryName
FROM Products
INNER JOIN Categories ON Products.CategoryID = Categories.CategoryID;
--LEFT JOIN
SELECT column_name(s)
FROM table1
LEFT JOIN table2
ON table1.column_name = table2.column_name;
--RIGHT JOIN
SELECT column_name(s)
FROM table1
RIGHT JOIN table2
ON table1.column_name = table2.column_name;
--FULL OUTER JOINS
SELECT column_name(s)
FROM table1
FULL OUTER JOIN table2
ON table1.column_name = table2.column_name
WHERE condition;
*/
--SQL SELF JOIN(NOI HAI BANG LAI VOI NHAU)
USE HowKteam AND USE student
SELECT * FROM STUDENTS,GIAOVIEN ;




